//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleReaderDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleReaderDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _100010 {
            get {
                object obj = ResourceManager.GetObject("_100010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _100011 {
            get {
                object obj = ResourceManager.GetObject("_100011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _100012 {
            get {
                object obj = ResourceManager.GetObject("_100012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10005 {
            get {
                object obj = ResourceManager.GetObject("_10005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10006 {
            get {
                object obj = ResourceManager.GetObject("_10006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10007 {
            get {
                object obj = ResourceManager.GetObject("_10007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10008 {
            get {
                object obj = ResourceManager.GetObject("_10008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10009 {
            get {
                object obj = ResourceManager.GetObject("_10009", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10010 {
            get {
                object obj = ResourceManager.GetObject("_10010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10011 {
            get {
                object obj = ResourceManager.GetObject("_10011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10012 {
            get {
                object obj = ResourceManager.GetObject("_10012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10013 {
            get {
                object obj = ResourceManager.GetObject("_10013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10014 {
            get {
                object obj = ResourceManager.GetObject("_10014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10015 {
            get {
                object obj = ResourceManager.GetObject("_10015", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10016 {
            get {
                object obj = ResourceManager.GetObject("_10016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10017 {
            get {
                object obj = ResourceManager.GetObject("_10017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10018 {
            get {
                object obj = ResourceManager.GetObject("_10018", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10020 {
            get {
                object obj = ResourceManager.GetObject("_10020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10021 {
            get {
                object obj = ResourceManager.GetObject("_10021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10021_1 {
            get {
                object obj = ResourceManager.GetObject("_10021_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10022 {
            get {
                object obj = ResourceManager.GetObject("_10022", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10023 {
            get {
                object obj = ResourceManager.GetObject("_10023", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10024 {
            get {
                object obj = ResourceManager.GetObject("10024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10025 {
            get {
                object obj = ResourceManager.GetObject("10025", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10026 {
            get {
                object obj = ResourceManager.GetObject("10026", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _loading {
            get {
                object obj = ResourceManager.GetObject("_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _return {
            get {
                object obj = ResourceManager.GetObject("_return", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 CRC Error 的本地化字符串。
        /// </summary>
        internal static string BaseFrame_1 {
            get {
                return ResourceManager.GetString("BaseFrame_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MID Error 的本地化字符串。
        /// </summary>
        internal static string BaseFrame_2 {
            get {
                return ResourceManager.GetString("BaseFrame_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control Code Error 的本地化字符串。
        /// </summary>
        internal static string BaseFrame_3 {
            get {
                return ResourceManager.GetString("BaseFrame_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State Error 的本地化字符串。
        /// </summary>
        internal static string BaseFrame_4 {
            get {
                return ResourceManager.GetString("BaseFrame_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code Queue is Full 的本地化字符串。
        /// </summary>
        internal static string BaseFrame_5 {
            get {
                return ResourceManager.GetString("BaseFrame_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incomplete Code 的本地化字符串。
        /// </summary>
        internal static string BaseFrame_6 {
            get {
                return ResourceManager.GetString("BaseFrame_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overflow 的本地化字符串。
        /// </summary>
        internal static string BaseFrame_7 {
            get {
                return ResourceManager.GetString("BaseFrame_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheck11 {
            get {
                object obj = ResourceManager.GetObject("btncheck11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheck12 {
            get {
                object obj = ResourceManager.GetObject("btncheck12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheckoff1 {
            get {
                object obj = ResourceManager.GetObject("btncheckoff1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheckoff11_ {
            get {
                object obj = ResourceManager.GetObject("btncheckoff11 ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheckoff2 {
            get {
                object obj = ResourceManager.GetObject("btncheckoff2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheckoff3 {
            get {
                object obj = ResourceManager.GetObject("btncheckoff3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheckoff4 {
            get {
                object obj = ResourceManager.GetObject("btncheckoff4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheckoff5 {
            get {
                object obj = ResourceManager.GetObject("btncheckoff5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheckoff6 {
            get {
                object obj = ResourceManager.GetObject("btncheckoff6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheckon1 {
            get {
                object obj = ResourceManager.GetObject("btncheckon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheckon11_ {
            get {
                object obj = ResourceManager.GetObject("btncheckon11 ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheckon2 {
            get {
                object obj = ResourceManager.GetObject("btncheckon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheckon3 {
            get {
                object obj = ResourceManager.GetObject("btncheckon3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheckon4 {
            get {
                object obj = ResourceManager.GetObject("btncheckon4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheckon5 {
            get {
                object obj = ResourceManager.GetObject("btncheckon5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btncheckon6 {
            get {
                object obj = ResourceManager.GetObject("btncheckon6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Not support this baud rate 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_02_1 {
            get {
                return ResourceManager.GetString("Frame_0001_02_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP Parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_04_1 {
            get {
                return ResourceManager.GetString("Frame_0001_04_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP Parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_07_1 {
            get {
                return ResourceManager.GetString("Frame_0001_07_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port parameter reader hardware is not supported 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_09_1 {
            get {
                return ResourceManager.GetString("Frame_0001_09_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not support this Port parameter 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_0B_1 {
            get {
                return ResourceManager.GetString("Frame_0001_0B_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter is missing 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_0B_2 {
            get {
                return ResourceManager.GetString("Frame_0001_0B_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not support Wiegand Interface 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_0D_1 {
            get {
                return ResourceManager.GetString("Frame_0001_0D_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not suoport this Wiegand communication format 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_0D_2 {
            get {
                return ResourceManager.GetString("Frame_0001_0D_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The reader does not support the data content 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_0D_3 {
            get {
                return ResourceManager.GetString("Frame_0001_0D_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RTC setup failed 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_10_1 {
            get {
                return ResourceManager.GetString("Frame_0001_10_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reader MAC parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_13_1 {
            get {
                return ResourceManager.GetString("Frame_0001_13_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|Hardware not supported 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_31_1 {
            get {
                return ResourceManager.GetString("Frame_0001_31_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|Connect successfully 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_33_0 {
            get {
                return ResourceManager.GetString("Frame_0001_33_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|Connection failed 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_33_1 {
            get {
                return ResourceManager.GetString("Frame_0001_33_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0|Closed 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_37_0 {
            get {
                return ResourceManager.GetString("Frame_0001_37_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|Open 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_37_1 {
            get {
                return ResourceManager.GetString("Frame_0001_37_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success! 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_48_0 {
            get {
                return ResourceManager.GetString("Frame_0001_48_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter error! 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_48_1 {
            get {
                return ResourceManager.GetString("Frame_0001_48_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save failed! 的本地化字符串。
        /// </summary>
        internal static string Frame_0001_48_2 {
            get {
                return ResourceManager.GetString("Frame_0001_48_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not support this Port parameter 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_01_1 {
            get {
                return ResourceManager.GetString("Frame_0010_01_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not support this Power parameter 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_01_2 {
            get {
                return ResourceManager.GetString("Frame_0010_01_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not support this Frequency range parameter 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_03_1 {
            get {
                return ResourceManager.GetString("Frame_0010_03_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel number is out of the current band range 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_05_1 {
            get {
                return ResourceManager.GetString("Frame_0010_05_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid number of frequencies 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_05_2 {
            get {
                return ResourceManager.GetString("Frame_0010_05_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_05_3 {
            get {
                return ResourceManager.GetString("Frame_0010_05_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 this antenna port does not exist 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_07_1 {
            get {
                return ResourceManager.GetString("Frame_0010_07_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_09_1 {
            get {
                return ResourceManager.GetString("Frame_0010_09_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The device does not support the baseband rate 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_0B_1 {
            get {
                return ResourceManager.GetString("Frame_0010_0B_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Q value parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_0B_2 {
            get {
                return ResourceManager.GetString("Frame_0010_0B_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Session parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_0B_3 {
            get {
                return ResourceManager.GetString("Frame_0010_0B_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventory parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_0B_4 {
            get {
                return ResourceManager.GetString("Frame_0010_0B_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_0B_5 {
            get {
                return ResourceManager.GetString("Frame_0010_0B_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_0D_1 {
            get {
                return ResourceManager.GetString("Frame_0010_0D_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_0D_2 {
            get {
                return ResourceManager.GetString("Frame_0010_0D_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antenna port parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_10_1 {
            get {
                return ResourceManager.GetString("Frame_0010_10_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Read parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_10_2 {
            get {
                return ResourceManager.GetString("Frame_0010_10_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TID reading error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_10_3 {
            get {
                return ResourceManager.GetString("Frame_0010_10_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Userdata reading error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_10_4 {
            get {
                return ResourceManager.GetString("Frame_0010_10_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved Area data reading error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_10_5 {
            get {
                return ResourceManager.GetString("Frame_0010_10_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other parameter errors 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_10_6 {
            get {
                return ResourceManager.GetString("Frame_0010_10_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antenna port parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_11_1 {
            get {
                return ResourceManager.GetString("Frame_0010_11_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag missing 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_11_10 {
            get {
                return ResourceManager.GetString("Frame_0010_11_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command sending error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_11_11 {
            get {
                return ResourceManager.GetString("Frame_0010_11_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter selection error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_11_2 {
            get {
                return ResourceManager.GetString("Frame_0010_11_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter input error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_11_3 {
            get {
                return ResourceManager.GetString("Frame_0010_11_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRC error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_11_4 {
            get {
                return ResourceManager.GetString("Frame_0010_11_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power shortage 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_11_5 {
            get {
                return ResourceManager.GetString("Frame_0010_11_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Overflow 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_11_6 {
            get {
                return ResourceManager.GetString("Frame_0010_11_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data area is locked 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_11_7 {
            get {
                return ResourceManager.GetString("Frame_0010_11_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access password error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_11_8 {
            get {
                return ResourceManager.GetString("Frame_0010_11_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other tag mistakes 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_11_9 {
            get {
                return ResourceManager.GetString("Frame_0010_11_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antenna port parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_12_1 {
            get {
                return ResourceManager.GetString("Frame_0010_12_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Labels are missing 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_12_10 {
            get {
                return ResourceManager.GetString("Frame_0010_12_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The reader sends a command error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_12_11 {
            get {
                return ResourceManager.GetString("Frame_0010_12_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_12_2 {
            get {
                return ResourceManager.GetString("Frame_0010_12_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock operating parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_12_3 {
            get {
                return ResourceManager.GetString("Frame_0010_12_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRC error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_12_4 {
            get {
                return ResourceManager.GetString("Frame_0010_12_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 underpower 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_12_5 {
            get {
                return ResourceManager.GetString("Frame_0010_12_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Overflow 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_12_6 {
            get {
                return ResourceManager.GetString("Frame_0010_12_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data area is locked 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_12_7 {
            get {
                return ResourceManager.GetString("Frame_0010_12_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access password error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_12_8 {
            get {
                return ResourceManager.GetString("Frame_0010_12_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other tag mistakes 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_12_9 {
            get {
                return ResourceManager.GetString("Frame_0010_12_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antenna port parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_13_1 {
            get {
                return ResourceManager.GetString("Frame_0010_13_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_13_2 {
            get {
                return ResourceManager.GetString("Frame_0010_13_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRC error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_13_3 {
            get {
                return ResourceManager.GetString("Frame_0010_13_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 underpower 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_13_4 {
            get {
                return ResourceManager.GetString("Frame_0010_13_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inactivated password error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_13_5 {
            get {
                return ResourceManager.GetString("Frame_0010_13_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other tag mistakes 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_13_6 {
            get {
                return ResourceManager.GetString("Frame_0010_13_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Labels are missing 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_13_7 {
            get {
                return ResourceManager.GetString("Frame_0010_13_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The reader sends a command error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_13_8 {
            get {
                return ResourceManager.GetString("Frame_0010_13_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_20_0 {
            get {
                return ResourceManager.GetString("Frame_0010_20_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antenna port parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_20_1 {
            get {
                return ResourceManager.GetString("Frame_0010_20_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reader failed to send instructions 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_20_10 {
            get {
                return ResourceManager.GetString("Frame_0010_20_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong parameter selection 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_20_2 {
            get {
                return ResourceManager.GetString("Frame_0010_20_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong parameter Untraceable 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_20_3 {
            get {
                return ResourceManager.GetString("Frame_0010_20_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRC check error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_20_4 {
            get {
                return ResourceManager.GetString("Frame_0010_20_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power shortage 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_20_5 {
            get {
                return ResourceManager.GetString("Frame_0010_20_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_20_6 {
            get {
                return ResourceManager.GetString("Frame_0010_20_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported instructions 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_20_7 {
            get {
                return ResourceManager.GetString("Frame_0010_20_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other label errors 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_20_8 {
            get {
                return ResourceManager.GetString("Frame_0010_20_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Label loss 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_20_9 {
            get {
                return ResourceManager.GetString("Frame_0010_20_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antenna port parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_40_1 {
            get {
                return ResourceManager.GetString("Frame_0010_40_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read the contents of parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_40_2 {
            get {
                return ResourceManager.GetString("Frame_0010_40_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter error reading the user data area 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_40_3 {
            get {
                return ResourceManager.GetString("Frame_0010_40_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antenna port parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_41_1 {
            get {
                return ResourceManager.GetString("Frame_0010_41_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_41_2 {
            get {
                return ResourceManager.GetString("Frame_0010_41_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antenna port parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_42_1 {
            get {
                return ResourceManager.GetString("Frame_0010_42_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_42_2 {
            get {
                return ResourceManager.GetString("Frame_0010_42_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antenna port parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_50_1 {
            get {
                return ResourceManager.GetString("Frame_0010_50_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Read parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_50_2 {
            get {
                return ResourceManager.GetString("Frame_0010_50_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TID reading error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_50_3 {
            get {
                return ResourceManager.GetString("Frame_0010_50_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserData Area error reading error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_50_4 {
            get {
                return ResourceManager.GetString("Frame_0010_50_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_50_5 {
            get {
                return ResourceManager.GetString("Frame_0010_50_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antenna port parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_51_1 {
            get {
                return ResourceManager.GetString("Frame_0010_51_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identification failure 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_51_10 {
            get {
                return ResourceManager.GetString("Frame_0010_51_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other tag mistakes 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_51_11 {
            get {
                return ResourceManager.GetString("Frame_0010_51_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Labels are missing 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_51_12 {
            get {
                return ResourceManager.GetString("Frame_0010_51_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command sending error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_51_13 {
            get {
                return ResourceManager.GetString("Frame_0010_51_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_51_2 {
            get {
                return ResourceManager.GetString("Frame_0010_51_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter input error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_51_3 {
            get {
                return ResourceManager.GetString("Frame_0010_51_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRC error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_51_4 {
            get {
                return ResourceManager.GetString("Frame_0010_51_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 underpower 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_51_5 {
            get {
                return ResourceManager.GetString("Frame_0010_51_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Overflow 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_51_6 {
            get {
                return ResourceManager.GetString("Frame_0010_51_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data area locked 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_51_7 {
            get {
                return ResourceManager.GetString("Frame_0010_51_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access password error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_51_8 {
            get {
                return ResourceManager.GetString("Frame_0010_51_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient permissions 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_51_9 {
            get {
                return ResourceManager.GetString("Frame_0010_51_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antenna port parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_52_1 {
            get {
                return ResourceManager.GetString("Frame_0010_52_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identification failure 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_52_10 {
            get {
                return ResourceManager.GetString("Frame_0010_52_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other tag error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_52_11 {
            get {
                return ResourceManager.GetString("Frame_0010_52_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag data missing 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_52_12 {
            get {
                return ResourceManager.GetString("Frame_0010_52_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The reader sends a command error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_52_13 {
            get {
                return ResourceManager.GetString("Frame_0010_52_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_52_2 {
            get {
                return ResourceManager.GetString("Frame_0010_52_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock operating parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_52_3 {
            get {
                return ResourceManager.GetString("Frame_0010_52_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRC error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_52_4 {
            get {
                return ResourceManager.GetString("Frame_0010_52_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Underpower 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_52_5 {
            get {
                return ResourceManager.GetString("Frame_0010_52_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Overflow 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_52_6 {
            get {
                return ResourceManager.GetString("Frame_0010_52_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data area locked 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_52_7 {
            get {
                return ResourceManager.GetString("Frame_0010_52_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access password error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_52_8 {
            get {
                return ResourceManager.GetString("Frame_0010_52_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient permissions 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_52_9 {
            get {
                return ResourceManager.GetString("Frame_0010_52_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antenna port parameter error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_53_1 {
            get {
                return ResourceManager.GetString("Frame_0010_53_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command sending error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_53_10 {
            get {
                return ResourceManager.GetString("Frame_0010_53_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter selection error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_53_2 {
            get {
                return ResourceManager.GetString("Frame_0010_53_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRC error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_53_3 {
            get {
                return ResourceManager.GetString("Frame_0010_53_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 underpower 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_53_4 {
            get {
                return ResourceManager.GetString("Frame_0010_53_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inactivated password error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_53_5 {
            get {
                return ResourceManager.GetString("Frame_0010_53_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient permissions 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_53_6 {
            get {
                return ResourceManager.GetString("Frame_0010_53_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identification failure 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_53_7 {
            get {
                return ResourceManager.GetString("Frame_0010_53_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other tag error 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_53_8 {
            get {
                return ResourceManager.GetString("Frame_0010_53_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag data missing 的本地化字符串。
        /// </summary>
        internal static string Frame_0010_53_9 {
            get {
                return ResourceManager.GetString("Frame_0010_53_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not support this Frequency parameter 的本地化字符串。
        /// </summary>
        internal static string Frame_0101_00_1 {
            get {
                return ResourceManager.GetString("Frame_0101_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not support this Port parameter 的本地化字符串。
        /// </summary>
        internal static string Frame_0101_00_2 {
            get {
                return ResourceManager.GetString("Frame_0101_00_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLL lock failure 的本地化字符串。
        /// </summary>
        internal static string Frame_0101_00_3 {
            get {
                return ResourceManager.GetString("Frame_0101_00_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 save parameters failed 的本地化字符串。
        /// </summary>
        internal static string Frame_0101_01_1 {
            get {
                return ResourceManager.GetString("Frame_0101_01_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 save parameters failed 的本地化字符串。
        /// </summary>
        internal static string Frame_0101_03_1 {
            get {
                return ResourceManager.GetString("Frame_0101_03_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 save parameters failed 的本地化字符串。
        /// </summary>
        internal static string Frame_0101_06_1 {
            get {
                return ResourceManager.GetString("Frame_0101_06_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap waiting {
            get {
                object obj = ResourceManager.GetObject("waiting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
