namespace SimpleReaderDemo
{
    partial class myButtonCheck
    {
        /// <summary> 
        /// Required designer variables.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up all resources in use.
        /// </summary>
        /// <param name="disposing">If the managed resource should be released, true; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the component designer

        /// <summary> 
        /// The designer supports the required method-do not 
        /// use the code editor to modify the contents of this method.
        /// </summary>
        private void InitializeComponent()
        {
            this.SuspendLayout();
            // 
            // myButtonCheck
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Name = "myButtonCheck";
            this.Click += new System.EventHandler(this.myButtonCheck_Click);
            this.ResumeLayout(false);

        }

        #endregion
    }
}
